### ISSUE TITLE
Slave not working

### ISSUE THREAD

**Issue by inte-n-t** [turingmachine/omxplayer-sync#100]
I have created the following .sh script to be executed on startup using /etc/rc.local it works perfectly when it is opening the master however when I change it to slave, the desktop boots up instead. If I then go an run `bash omxplayer-sync -lu -a fill /home/pi/mov/AA.mp4` directly in terminal nothing happens... 

I have run omxsync successfully on many projects before but for some reason, all my new slaves have stopped working now. 

Any help would be greatly appreciated!!

```
##Master
#！/bin/bash
omxplayer-sync -mu -a fill /home/pi/mov/AA.mp4
```

```
##Slave
#！/bin/bash
omxplayer-sync -lu -a fill /home/pi/mov/AA.mp4
```

```
##/etc/rc.local code 
sudo bash /home/pi/video.sh &
```

**Comment by ramazansubasi** [comment]
Did you solve this problem? Because I have some problem.

**Comment by spleeen1** [comment]
me too. any help would be great!
