### ISSUE TITLE
OMXplayer build link broken

### ISSUE THREAD

**Issue by ooftv** [turingmachine/omxplayer-sync#101]
wget http://omxplayer.sconde.net/builds/omxplayer_0.3.7~git20160713~66f9076_armhf.deb

This url returns a 404

**Comment by hitesh83** [comment]
as per readme omx deb is updated and new url is as below
`wget https://github.com/magdesign/PocketVJ-CP-v3/raw/master/sync/omxplayer_0.3.7-git20170130-62fb580_armhf.deb`

**Comment by ooftv** [comment]
Thanks, I was able to get it working with the latest version of OMXPlayer available from apt-get:

omxplayer - Commandline multimedia player for the Raspberry Pi
        Build date: Thu, 01 Aug 2019 12:50:43 +0000
        Version   : f543a0d [master]
        Repository: https://github.com/popcornmix/omxplayer.git
