### ISSUE TITLE
How can I upload new video's to the omxplayer-sync directory on my pi's?

### ISSUE THREAD

**Issue by bjente** [turingmachine/omxplayer-sync#105]
Hello all,

I have an urgent question. I cannot figure out how I can upload my own videos to the omxplayer-sync video directory on my pi's. I want to sync 4 different videos on 4 different screens. The pi's have a static IP, one is master, others are slave. Theyre connected through a switch with ethernet cables. Any helpt would be appreciated.

**Comment by magdesign** [comment]
please do not post your issues 2x

**Comment by pyfave** [comment]
https://askubuntu.com/questions/781963/simple-samba-share-no-password
