### ISSUE TITLE
How to upload NEW video to omxplayer-sync video directory on pi's?

### ISSUE THREAD

**Issue by bjente** [turingmachine/omxplayer-sync#106]
Hello all,

I have an urgent question. I cannot figure out how I can upload my own videos to the omxplayer-sync video directory on my pi's. I want to sync 4 different videos on 4 different screens. The pi's have a static IP, one is master, others are slave. Theyre connected through a switch with ethernet cables. Any helpt would be appreciated.

**Comment by himijendrix24** [comment]
Start sftp and ssh connection to the raspberrys (bitvise-ssh on windows, linux from terminal).
Replace the videofile that is played by script that should be running on your raspberries.
Restart.
How is omxplayer-sync currently run on your setup?

Remember: "The filename on the master and the slave must be exactly the same."

**Comment by pramodmadhav** [comment]
you can also use filezilla from your windows

**Comment by magdesign** [comment]
This is not an omxplayer-sync realated issue.
Look in the RPI forums for help!
or considering buying a [PocketVJ](https://www.pocketvj.com) where things like this are implemented for the users.
