### ISSUE TITLE
Distorted sound

### ISSUE THREAD

**Issue by plagasul** [turingmachine/omxplayer-sync#118]
Hello,

I am getting a distorted sound -perhaps low-bitrate like- when playing a video through omxplayer-sync but NOT when I play it directly with omxplayer

I run:

`omxplayer-sync -muv video.mp4` (also -luv)

but I get the same sound if I do plainly:

`omxplayer-sync video.mp4`

To run the video with omxplayer I use the following (and it sounds good)

`omxplayer video.mp4`

I am on a rpi 4 model B with:

- raspbian 10 (buster)
- omxplayer Version: f543a0d [master], Build date: Thu, 01 Aug 2019 12:50:43 +0000

I tried different videos, such as:

https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_10mb.mp4
http://twitch-event-engineering-public.s3.amazonaws.com/sync-footage/Sync-Footage-V1-H264.mp4

I check the sound via the stereo minijack output on both cases.

Any ideas?

Thank you

**Comment by magdesign** [comment]
Did you tried with setting the audio output in the command like:

`/usr/bin/omxplayer-sync -mu -o local video.mp4`

omxplayer-sync is not tested on RPI4, 
on RPI3 we have a similar issue when sound is played through hdmi and mini jack.
please test and report back!

**Comment by plagasul** [comment]
Specifying the audio output as suggested fixes the sound :D 

I still haven't seen the video (headless) will test tomorrow morning with an external monitor and confirm.

**Comment by plagasul** [comment]
I confirm it works :)
