### ISSUE TITLE
Movie Unavailable from Master

### ISSUE THREAD

**Issue by reillydonovan** [turingmachine/omxplayer-sync#18]
I'm having a strange issue concerning the clients responding to the master.
I had this working before with all of the pi's connected over a local switcher no problem. 
I then tried connecting the switcher to my router so that I could connect all of the pis to the internet, in doing this I had to change all of the static network settings for all of the pis so they would correspond to the appropriate network, gateway, broadcast, etc. settings for the router.  
So I managed to get all of the pis to connect to the internet through the switcher connected to the router.  I can ping each pi respectively from each other successfully, and I can connect to them via netatalk through my mac and execute commands, however whenever I try to launch omxplayer-sync clients, they seem to refuse to recognize the master that is playing back.  Do you have any suggestions on what could resolve this?  Please let me know if this makes sense and if you need any more supporting information.  Thanks!

**Comment by turingmachine** [comment]
Hi Donovan

I assume this issue has been resolved?
