### ISSUE TITLE
Sync Playlist with Trigger

### ISSUE THREAD

**Issue by reillydonovan** [turingmachine/omxplayer-sync#19]
This software = amazing.
Quick question, is there a way to set up a playlist with it and transition or cut to the next video in the list using a keypad trigger like the spacebar or something?  Then have all corresponding pi clients transition or cut and sync with the next item in the playlist?  Thanks again for such great stuff to work with!

**Comment by magdesign** [comment]
The playlist thing is possible and we have it on the to do list. We once had a prototype with a thumbnailbrowser who had a checkmark to select the videos for playlist.
First we have to sell some pocketvj.com to generate a income so we can invest more time for programming. There is already a solution where you can trigger videos named with 01....mp4, 02....mp4 over a webbrowser: https://github.com/magdesign/PocketVJ
with the old Pi model, transition is not possible, but with the new one it might be possible.
Nice to see that you like our software ;-)

**Comment by turingmachine** [comment]
You could kill the omxplayer and omxplayer.bin processes. This would force the master to proceed to the next video in the playlist. All slaves would re-sync to the new movie imediately.

**Comment by turingmachine** [comment]
Basically one would need to listen for a key event and kill the mentioned processes.
Pull requests are welcome! :)

**Comment by reillydonovan** [comment]
How do you kill the omxplayer and omxplayer.bin processes?

**Comment by reillydonovan** [comment]
I've tried pkill -9 omx and killall omxplayer.bin, it kills the process but the loop starts again, any thoughts?

**Comment by reillydonovan** [comment]
I've been able to kill the processes by typing:
ps -Al
then kill ****, * being whatever process omxplayer.bin and omxplayer are, however it requires killing both processes once then omxplayer a third time.  Is there an easier way to do this with a simple command instead of going into the listed processes and manually iding the number of the process to kill?  Thanks again!

**Comment by reillydonovan** [comment]
my apologies for all the comments... I believe I found the solution in PocketVJ's omxkill.py
#!/bin/bash
exec > /dev/null 2>&1
sudo pkill -9 -f omxplayer-sync
sudo pkill -9 -f omxplayer
sudo pkill -9 -f omxplayer.bin

Thanks again!
