### ISSUE TITLE
general questions

### ISSUE THREAD

**Issue by laboratories** [turingmachine/omxplayer-sync#20]
I have installed your sync system and am very impressed that it works...
I will spend the next few days digging in to it - and try to learn how it works

but a quick question or two:

do you have any plans to update the system? (specifically the onxplayer build)
I am using a Raspberry Pi 2 (yay)
and I am wondering is a fresher build could utilize the new expanded resources of the RPi2
specifically to achieve better sync.
I am getting between two and four frame sync
and I am looking to achieve 1-2 frame sync (or better! as in scanline sync!! :-) )

also after playing a file for some time in a loop the sync can take up to 40 sec to be found
- is there anyway to minimize this? 
- and it would be great if there was not the pause/blackscreen while syncing ( work with artists ;-)

thank you for your efforts
most appreciated

garret

**Comment by laboratories** [comment]
and oh PS
on the current version of rasbian it seems that there is no need to install dbus as it is in the distro


G

**Comment by turingmachine** [comment]
If you start omxplayer-sync in verbose mode on the slave, what is the value of the moving_deviation? You could to try to lower the TOLERANCE variable at the top of the script. A tolerance of 0.25 means that omxplayer-sync won't sync unless the slave is 0.25 seconds (~6 frames) ahead or behind the master. So if you got constant deviations you could try to lower the TOLERANCE.

**Comment by turingmachine** [comment]
Is this still an open issue?
