### ISSUE TITLE
vimeo link indescription is dead

### ISSUE THREAD

**Issue by mxa** [turingmachine/omxplayer-sync#21]
I'd like to see the video. The link is dead. Is this project alive? Maybe it could be changed to https://vimeo.com/118376281 ?

**Comment by turingmachine** [comment]
The link needs to be changed to this video: https://vimeo.com/92041974
I also will include a link to your video, thank you.

**Comment by mxa** [comment]
Interesting! Not my video though. just searched for "omxplayer-sync" on vimeo and found it.

**Comment by magdesign** [comment]
I updated the link.
