### ISSUE TITLE
DBUS Error

### ISSUE THREAD

**Issue by mxa** [turingmachine/omxplayer-sync#22]
Hi @turingmachine . Thank you for omxplayer-sync, it is exactly what i was looking for.
I installed it and it runs like this:

    $ omxplayer-sync synctest.mp4 

but when started as a master, i get an error:

    $ omxplayer-sync -mov synctest.mp4 
    WARNING: dbus connection could not be established
    org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer2.omxplayer was not provided by any .service files
    WARNING: dbus connection could not be established
    org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer2.omxplayer was not provided by any .service files

    $ omxplayer --version
    omxplayer - Commandline multimedia player for the Raspberry Pi
        Build date: Thu, 15 May 2014 14:42:52 +0200
        Version   : 3176db4 [omxplayer-sync]
        Repository: UNKNOWN

**Comment by turingmachine** [comment]
Remove all files in /tmp that got 'omxplayer' in the filename and kill all running dbus instances. Try to restart omxplayer-sync after that. You must only use a single user to start omxplayer or omxplayer-sync respectively. If you did start it once as root and then try to start it as non-root, it will fail.

**Comment by mxa** [comment]
Still the same issue after cleaning the '/tmp' directory and 'sudo killall dbus-daemon'. will try complete clean install on a fresh raspbian.

**Comment by mxa** [comment]
ok, I got rid of the reeor by reinstalling everything from scratch. Here is a little bit more verbose version of the installing instructions:

install pexpect:

 sudo apt-get install python-pexpect
 sudo apt-get install python3-setuptools

install python bindings for DBUS https://github.com/LEW21/pydbus

 sudo wget https://github.com/LEW21/pydbus/archive/master.zip
 sudo unzip master.zip
 sudo rm master.zip
 cd pydbus-master/
 sudo chmod 777 setup.py
 sudo ./setup.py build
 sudo ./setup.py install


 sudo apt-get remove omxplayer
 sudo rm -rf /usr/bin/omxplayer /usr/bin/omxplayer.bin /usr/lib/omxplayer
 sudo wget -O- http://yokto.net/0/omxplayer/omxplayer-3176db4.tar.bz2 | sudo tar -C / -xjvf -
 sudo ln -sf /lib/arm-linux-gnueabihf/libpcre.so.3 /lib/arm-linux-gnueabihf/libpcre.so.1
 sudo wget -O /usr/bin/omxplayer-sync https://github.com/turingmachine/omxplayer-sync/raw/master /omxplayer-sync
 sudo chmod 0755 /usr/bin/omxplayer-sync
 sudo wget https://github.com/turingmachine/omxplayer-sync/raw/master/synctest.mp4

**Comment by mxa** [comment]
Now the same error appeared again. The only thing I changed was the filename and the way the startup script is launched. instead of calling it from /etc/profile i now use .bashrc to call it. I deleted the files in /tmp and restarted and get the same messages.

on the master and server:
WARNING: dbus connection could not be established
org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer2.omxplayer was not provided by any .service files.

**Comment by turingmachine** [comment]
What is you exact call to omxplayer-sync? Try to start omxplayer directly. What user are you using to play files? omxplayer tries to start it's own dbus server: https://github.com/popcornmix/omxplayer/blob/master/omxplayer#L50

**Comment by mxa** [comment]
Oh, this is so embarrassing. I was trying play back an .mpeg. It works well with the .mp4 version of the file. Sorry for the noise. The error message was not exactly helping me to trouble shoot this, but after seing that the test file works well, I realized what's the issue.
