### ISSUE TITLE
WARNING: current master file 'filename.mp4' is unavailable

### ISSUE THREAD

**Issue by jeffutv** [turingmachine/omxplayer-sync#25]
When testing omxplayer-sync, I can get two pis to sync correctly using the supplied synctest.mp4, but when I attempt to sync with other files, I get this issue:

WARNING: current master file 'filename.mp4' is unavailable

The filename updates to display the current file running as a master on the network, but the relay (perhaps a less politically loaded way to refer to 'slave') pi displays a loop of the above error.

The current file is 1080p 23.976 H264 .mp4 from Adobe Media Encoder with keyframes set to every 24 frames (which *should* set the GOP to 24 frames from the default 72).

**Comment by jeffutv** [comment]
I can only get the sync to work correctly if the master and relay have the exact same filenames. Is this correct?

**Comment by magdesign** [comment]
The filename must be exactly the same on master and on the slave.

If your sync does not work as mentioned above, make sure that the folder where the movie is placed only contains the movie and nothing else (e.g. no pictures, folder, other files)

**Comment by turingmachine** [comment]
This feature needs clarification in the README.
