### ISSUE TITLE
WARNING: omxplayer hangup detected, respawning omxplayer

### ISSUE THREAD

**Issue by coopak** [turingmachine/omxplayer-sync#27]
This error is produced every ~30s when running the provided synctest.mp4 via commands:

omxplayer-sync -mu synctest.mp4
omxplayer-sync -lu synctest.mp4

I tried changing TOLERANCE = 0.25 to TOLERANCE = 0.5, but this had no effect on the hangups. 

This is on a RPi 2. 

I don't see any other issues with this problem so I will continue to investigate my set up. I'll post back if I find a solution so others can avoid this.

**Comment by turingmachine** [comment]
The TOLERANCE setting has nothing to do with hangups occurring. A hangup is detected when the value of position_master does not change over a small period of time. Do the videos actually run on the screen?

**Comment by coopak** [comment]
Sorry for the delay. It took me longer than expected to narrow things down.

To answer your question, yes, both slaves would: (1) play OK on screen; (2) freeze on a random frame; (3) produce this error; (4) restart at 0:00; (5) immediately re-sync to the master via seek-pause-play (master never froze). This cycle happened every 20-30 seconds.

A large contributing problem turned out to be using the 'Pi 2' overclock preset in raspi-config. Removing that reduced this error dramatically. I now only experience a hangup on synctest.mp4 every few minutes.

**Comment by turingmachine** [comment]
omxplayer-sync is used in a commercial [product](http://www.pocketvj.com) based on RP2. omxplayer-sync runs without issues there. Do you have any external devices connected to the Pi, like WiFi dongles or similar?

**Comment by coopak** [comment]
Thanks for the link. 

Yes, I'm using WiFi dongles. After removing the overclock, I have an 8min video syncing with only the occasional hangup. Perhaps the dongles are causing the lingering hangups, but I'd have to test ethernet to know for certain.
