### ISSUE TITLE
multiple slaves

### ISSUE THREAD

**Issue by sq9** [turingmachine/omxplayer-sync#30]
can multiple slaves point to master, or can master have multiple ip destinations?

**Comment by turingmachine** [comment]
Yes, the master sends the current position by default to the address 255.255.255.255. Thus they are broadcasted within the current network and will be received by all connected slaves and any other connected network devices.

https://en.wikipedia.org/wiki/Broadcast_address

**Comment by chuco61** [comment]
is this an IP address I can use for my Broadcast? Does this also apply to gateway?
