### ISSUE TITLE
Rising deviation / slaves crash after longer playback

### ISSUE THREAD

**Issue by irrelevar** [turingmachine/omxplayer-sync#31]
Hello and thank you for this great software. 

I am trying to have three slaves and one master raspberry pi b+ playing a 40 min video synced. It works perfectly with very little deviation but after 1050 secs deviation rapidly increases and the slaves try to resync. However deviation stays over default tolerance so they try to resync again and again until they crash. Has anyone experienced this or knows a what could be causing this? Thank you for your reply

**Comment by turingmachine** [comment]
Can you confirm that the master is still sending position information? If the slave is started in verbose mode, does the value for position_master still change when the error occurs?

Please provide verbose output from the master and one slave as two [gists](gists.github.com) starting from second 1049 until resync on slaves occur.

**Comment by irrelevar** [comment]
thank you for getting back quickly.
here is the verbose output of master and slave:
https://gist.github.com/irrelevar/d696cbca24ccb012f470

as far as i can see the deviation increases while position_master and position_local still update yes

**Comment by turingmachine** [comment]
What are the values for TOLERANCE and SYNC_WINDOW? Can you provide the movies to me by any means? What kind of Raspery are you using and how are the devices connected? Do you have any USB devices attached? Please try again with only one master and one slave and connect them directly with a single ethernet cable and see if the error still occurs.

**Comment by irrelevar** [comment]
i tried it with different TOLERANCE and SYNC_WINDOW and experienced same errors  the values for the gists where TOLERANCE = 0.5 and SYNC_WINDOW = (-0.30, -0.25). I am using four Raspberry Pi B+ connected over ethernet switch. Only one usb keyboard / mouse is connected. Same problem with ssh from mac. I tried with master and slave connected directly with single ethernet cable and it the slave fails to sync several time before it crashes with omxplayer hangup detected. I am uploading two of the four movies now on dropbox now but it will take some time.

**Comment by irrelevar** [comment]
still experiencing multiple hangups without syncing correctly on the slave side. any idea how to fix this? your help is greatly appreciated.

**Comment by turingmachine** [comment]
Can you provide the links to the videos you uploaded? Do the videos play correctly? With what codec,  and bitrate are the videos encoded? Do hangups always occur at around 1000 seconds into the movie? Have to tried to test it with another video of the same length?

**Comment by irrelevar** [comment]
yes i have the same issue of hangups with other videos also with the testfile

**Comment by magdesign** [comment]
Do you have various resolutions on the 3 RPis?
Are you using some videos with audio and some not?
Do all 3 RPis have strong power supplys?
Did you tryed it with this branch: https://github.com/turingmachine/omxplayer-sync/blob/next/omxplayer-sync

**Comment by magdesign** [comment]
I tried to retrace this issue with two RPi2 directly connected over RJ45 and a 34min testfile.
Both RPi's have the same screen connected and its exactly the same video.
Mine is working perfectly fine, no rising deviation or any issues after 3h testing,
will test it for the next 48hours, but I guess your issue is hardware based.

**Comment by irrelevar** [comment]
Thank you for trying this out. What could be the hardware issue? I am using 4 same Rpi with same 16gb class 10 sd cards connected via RJ45 gigabit cable. Did you use h.264 codec? Which video resolution?

**Comment by magdesign** [comment]
I used 1280 x 720p videos, compressed with h264 VBR 10-12 mbit/s.
The screens have a resolution of 1680x1050, connected with HDMI cables.
Both Pi's have a Wifi dongle connected.
I connected them directly: https://vimeo.com/137133716

I will try it with 3 RPi's and a router and let you know the result, want to resolve this issue...

**Comment by irrelevar** [comment]
here is the link to the video i had trouble with. maybe you can have a try with it. 
https://www.dropbox.com/s/eo8ga9s9u4tnwae/murmur.mp4?dl=0

**Comment by burtonworldart** [comment]
I know this is an older thread but any help would be great solving the hangup issue. I'm running sync via wifi dongle on a home wifi network. Couldn't get videos to sync via RJ45 gigabit cable.  I will try connecting to router via an offline LAN network.   Wondering if anyone's used a usb to ethernet port connector?  Seems like the master/ slave connection won't happen for me if I unplug the wifi dongle.

Thanks

**Comment by turingmachine** [comment]
There is a new version of omxplayer-sync available with a much improved syncing system.
