### ISSUE TITLE
Playback in loop interrupted by a temporal quit

### ISSUE THREAD

**Issue by demmaone** [turingmachine/omxplayer-sync#32]
Hi, I all my videos quit for just a second after they complete the playback and before starting a new loop.
I´m using: omxplayer-sync -mu /home/pi/myfolder/myfile.mp4

Thanks in advance

**Comment by turingmachine** [comment]
Plase see (issue 23)https://github.com/turingmachine/omxplayer-sync/issues/23].

It would be possible to patch omxplayer-sync to use omxplayer's loop options if only a video is provided.
