### ISSUE TITLE
Omxplayer with --passthrough option rising 'hangup detect'

### ISSUE THREAD

**Issue by radames** [turingmachine/omxplayer-sync#33]
I'm trying to use the omxplayer-sync for a multichannel audio installation, with several Raspberry Pis.
I've added the the option `passthrough` in order to have a 5.1 audio output on the HDMI
`self.omxplayer_options.append("-p")`

When I try the sync, the script is rising the "hangup detect" and the audio file is not played or neither synced.

When I try the `omxplayer` , the pre-compiled one we should user for the omxplayer-sync, with the `-p` option the audio video is played properly with 5.1 surround.

Is there any way to overtake the hangup detection with the passthrough mode enabled?

**Comment by turingmachine** [comment]
Does sync work without the providing the "-p" option?

**Comment by radames** [comment]
the sync with ```-p``` option doesn't work,  it outputs a "hangup detect" error

**Comment by turingmachine** [comment]
Does sync work without the providing the "-p" option?

**Comment by radames** [comment]
Yes, the sync work perfect without the "-p" option.
Your pre-compile omxplayer works with "-p" option providing the surround audio, but only for one not synced RsPi.
