### ISSUE TITLE
New to Raspberry Pi

### ISSUE THREAD

**Issue by mrathai** [turingmachine/omxplayer-sync#35]
Hi, I am new to Raspberry Pis and desperately need your help!
I'm looking to sync two videos on two separate screens. They will be looped continually in a gallery space for an exhibition.

A few questions:
1. Is syncing still possible with 2x Model A+'s along with 2 USB to Ethernet adapters? Something like this: http://www.shoppingsquare.com.au/product.php?id=413965

2. Looking at the video you attached of the PocketVJ, is this also absolutely necessary for syncing?

Thank you so much.

**Comment by turingmachine** [comment]
Syncing should be possible with 2x model A+'s without USB to ethernet adapters, as the Rasperry's already provide ethernet ports. You don't need the PocketVJ product for syncing. PocketVJ is a full featured product that uses omxplayer-sync as the default media player.
