### ISSUE TITLE
WARNING: dbus connection could not be established

### ISSUE THREAD

**Issue by Francesc116** [turingmachine/omxplayer-sync#36]
Hello,

I want to synchronise two raspberry pi 2 with omxplayer-sync, but I have no success for the moment.
Even, playing the synctest.mp4 video in 1 raspberry I get the warning

WARNING: dbus connection could not be established
org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer2.omxplayer was not provided by any .service files

I reinstalled everything (raspbian from NOOBS) following this tutorial

https://www.uni-weimar.de/medien/wiki/Automation/RaspberryPi

The video plays, but I always get this warning. I guess that's the reason the sync doesn't work when I try with 2 raspberry.

I would appreciate any help!

PS: I saw someone had a similar problem https://github.com/turingmachine/omxplayer-sync/issues/22, but I can't fix deleting the /temp dir, etc.

**Comment by Francesc116** [comment]
I'm using the user "pi" all the time, both for installing and playing the video.

**Comment by Francesc116** [comment]
I reinstall everything again with root. Same problem.

1. I install raspbian from NOOBS

2. I update the OS
sudo su
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
sudo apt-get install raspberrypi-net-mods

3. I update the "Fimware"
sudo apt-get install git
wget https://raw.github.com/Hexxeh/rpi-update/master/rpi-update -O /usr/bin/rpi-update && sudo chmod +x /usr/bin/rpi-update
sudo rpi-update

4. reboot
sudo reboot

5. I install pexpect
sudo su
sudo apt-get install python-pexpect

6. I install python bindings for DBUS (I create the dir "pydbus-master" in "/home/pi". I guess that can't be the problem).
sudo apt-get install python3-setuptools
sudo cd /home/pi
sudo wget https://github.com/LEW21/pydbus/archive/master.zip
sudo unzip master.zip
rm master.zip
cd pydbus-master/
sudo chmod 777 setup.py
sudo ./setup.py build
sudo ./setup.py install

7. Finally I install omxplayer-sync from yokto.net
sudo apt-get remove omxplayer
sudo rm -rf /usr/bin/omxplayer /usr/bin/omxplayer.bin /usr/lib/omxplayer
sudo wget -O- http://yokto.net/0/omxplayer/omxplayer-3176db4.tar.bz2 | sudo tar -C / -xjvf -
sudo ln -sf /lib/arm-linux-gnueabihf/libpcre.so.3 /lib/arm-linux-gnueabihf/libpcre.so.1
sudo wget -O /usr/bin/omxplayer-sync https://github.com/turingmachine/omxplayer-sync/raw/master/omxplayer-sync
sudo chmod 0755 /usr/bin/omxplayer-sync

8. I download the test video and put it in a empty dir
sudo cd /home/pi/Videos
sudo wget https://github.com/turingmachine/omxplayer-sync/raw/master/synctest.mp4

9. I play the video (just to try it works fine, before starting with the synchronisation)
sudo omxplayer-sync -mbv synctest.mp4

The video plays, but I get the message:

WARNING: dbus connection could not be established
org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer2.omxplayer was not provided by any .service files

I guess, this is the reason it doesn't work when I try to sync 2 raspberry later.

I'm desperate!! :)

**Comment by Francesc116** [comment]
No one..?
Really, anyone is using this software with Raspbian Jessie? It doesn't work at all.

**Comment by turingmachine** [comment]
In step 6 you install python bindings by source. You should install the python bindings with apt-get:
```
sudo apt-get install python-dbus
```

**Comment by Francesc116** [comment]
Thanks for your answer turingmachine. I tried that, but with any success. I have made a new fresh installation, and it seems python-dbus is installed before arriving to the step 6. I think there is something wrong with the Raspbian Jessie version.

In details:

1, // I install a fresh Raspbian from NOOBS_v1_5_0. So, the version is Raspbian Jessie.
   // I configure put the wifi password

2.  // I update the OS
$ sudo su
$ sudo apt-get update
$ sudo apt-get upgrade
$ sudo apt-get dist-upgrade
$ sudo apt-get install raspberrypi-net-mods

 3. // I update the "Fimware"
$ sudo apt-get install git
$ wget https://raw.github.com/Hexxeh/rpi-update/master/rpi-update -O /usr/bin/rpi-update && sudo chmod +x /usr/bin/rpi-update
$  sudo rpi-update

4. // reboot
$ sudo reboot

5. // I install pexpect
$ sudo su
$ sudo apt-get install python-pexpect

6. //  I install python-dbus
$ sudo apt-get install python-dbus

---> but It says python-dbus is already the newest version.

7. // Finally I install omxplayer-sync from yokto.net
$ sudo apt-get remove omxplayer
$ sudo rm -rf /usr/bin/omxplayer /usr/bin/omxplayer.bin /usr/lib/omxplayer
$ sudo wget -O- http://yokto.net/0/omxplayer/omxplayer-3176db4.tar.bz2 | sudo tar -C / -xjvf -
$ sudo ln -sf /lib/arm-linux-gnueabihf/libpcre.so.3 /lib/arm-linux-gnueabihf/libpcre.so.1
$ sudo wget -O /usr/bin/omxplayer-sync https://github.com/turingmachine/omxplayer-sync/raw/master/omxplayer-sync
$ sudo chmod 0755 /usr/bin/omxplayer-sync

8. I download the test video and put it in a empty dir
$  cd /home/pi/Videos
$ sudo wget https://github.com/turingmachine/omxplayer-sync/raw/master/synctest.mp4

9. // reboot again
$  sudo reboot

10. // I play the video (just to try it works fine, before starting with the synchronisation)
$  sudo su
$  cd /home/pi/Videos
$  sudo omxplayer-sync -mbv synctest.mp4

WARNING: dbus connection could not be established
org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer2.omxplayer was not provided by any .service files

Should I receive this warning? Should the sync works with this warning?

**Comment by turingmachine** [comment]
Are you able to play a movie with omxplayer directly?

i.e. ```omxplayer synctest.mp4```

**Comment by Francesc116** [comment]
Yes, without problems.

omxplayer synctest.mp4 --> works, no WARNINGS

omxplayer-sync -mbv synctest.mp4 --> works, with the dbus WARNING

**Comment by turingmachine** [comment]
I guess nobody tried this on jessie yet. Can you try with raspbian wheezy?

**Comment by Francesc116** [comment]
Yes, with Wheezy works. With Jessie it doesn't.

Thanks!

**Comment by burtonworldart** [comment]
Francesc116.  I followed your lead for Wheezy and have almost got it working.  However I get a "WARNING: unable to get current filename from master"  from the -luv (slave) Pi.  Not sure if this is a dbus issue but I also tried the sudo apt-get install python-dbus.  Did you run into or resolve this warning?  i tried Step 7 as sudo but had to su to root to get anything to work.

**Comment by Francesc116** [comment]
It seems a network problem, or files with different name. There are some solved issues with this error.
Almost working? What have you changed? I can test it, my network configuration is fine (in fact, the sync works with Wheezy without issues).

**Comment by burtonworldart** [comment]
only changes I made were: 
did not install <sudo apt-get install raspberrypi-net-mods>
I ran Step 7 all as root because as pi using sudo user had conflicting error. (can't remember error)
I have modified my /etc/network/interfaces following these instructions and think that could be the source of my trouble : http://raspberrypihq.com/how-to-add-wifi-to-the-raspberry-pi/
Files are the same name and in identical folder with no other content.

**Comment by Francesc116** [comment]
If you follow the steps it works in Wheezy. In Jeesie, nothing to do. It doesn't work.
I configure the wifi at the step 1. Without internet connection, it's not possible to install the packages.

Step 1:
- Install a fresh Wheezy 3.18
- Configure the wifi from Command line editing "wpa_supplicant.conf" http://thepihut.com/blogs/raspberry-pi-tutorials/16018016-how-to-setup-wifi-on-the-raspberry-pi-raspbian

If you do this in all your Raspberry, they will be in the same network. If you have 2 Raspberry using your wifi connection, by default, if you don't touch anything, they are automatically in the same network. Of course, later you can try to assign static IP or not to use the wifi.

I hope it helps.

**Comment by burtonworldart** [comment]
Thanks,
This was helpful to find a better way to setup wifi.  

Did you delete the network={.......}  in /etc/wpa_supplicant.conf file after setting up omxplayer-sync? Does that matter maybe?  Conflict between ethernet and wifi?
  
I used a fresh version of Wheezy 3.18 but still have "network unreachable" error upon playing 
omxplayer-sync -mbv syncretist.mp4.

I did solve the dbus error however:
//step 7: 
When I ran as pi user with sudo in front of each line I got your bus error.
instead of sudo i front of each line I ran each line from root (sudo su). 
              example:
                 $ sudo su
                 $ apt-get remove omxplayer
                 $ rm -rf /usr/bin/omxplayer /usr/bin/omxplayer.bin /usr/lib/omxplayer 
Once I reran each line the movies played OK individually.

**Comment by Francesc116** [comment]
> Did you delete the network={.......} in /etc/wpa_supplicant.conf file after setting up omxplayer-sync? Does that matter maybe? Conflict between ethernet and wifi?

I haven't deleted it. I'm testing the sync via wifi.

> I did solve the dbus error however

I get the dbus error with Rapsbian Jessie. With Raspbian Wheezie, my steps work perfect to me.

**Comment by burtonworldart** [comment]
I know you are still testing this on Jessie and I thank you for your time.  Looks like Turingmachine is slower to respond.  I followed your steps for Wheezy 3.18 exactly.  Same filename, same location, calling omxplayer-sync exactly the same (except flags -muv on Pi A and -luv Pi B).  Same error.  <connect : Network is unreachable>  

After error I tried 
On Pi A

sudo ip ad add 10.0.0.10/24 dev eth0
On Pi B

sudo ip ad add 10.0.0.20/24 dev eth0
To test from A to B

ping 10.0.0.20
To test from B to A

ping 10.0.0.10 

100% packet swapping. 

What on Earth am I missing?  Still running Wheezy 3.18

**Comment by magdesign** [comment]
I'm running it on Jessie without any issues. 
- Did you install python-dbus ? you can try to install all depencies mentioned here: https://github.com/magdesign/PocketVJ-CP-v3
- Is the network cable connected when you boot up, because there is a known issue when omxplayer-sync is already running and you connect network later on, it does not recognise.
- omxplayer-sync was never tested to work with wifi.
- always use fixed Ip addresses.

**Comment by Francesc116** [comment]
Hi!

> Did you install python-dbus ? 
Yes, I detailed all my steps:

6.- // I install python-dbus
$ sudo apt-get install python-dbus
---> but It says python-dbus is already the newest version.

Maybe that's the problem. The python-dbus version.

> Is the network cable connected when you boot up
yes

> omxplayer-sync was never tested to work with wifi.
I tried with ethernet too

> always use fixed Ip addresses
yes

I will try with that version of python-dbus.

Thanks

**Comment by barlaensdoonn** [comment]
Last time I used omxplayer-sync was on a Wheezy distro, and sync over wifi worked no problem, although ethernet obviously performed better.

Also worth noting is that setting a static IP address in Jessie is slightly different than Wheezy, as per [this thread](https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=117350&p=804580). Seems it is recommended to leave /etc/network/interfaces as is and modify /etc/dhcpcd.conf instead, even if modifying the interfaces file still works in some cases.

**Comment by magdesign** [comment]
Is this still an issue ?

**Comment by selcukartut** [comment]
dear Francesc116, maybe it is due to the resolution of the videos. I have just realized that omxplayer does not allow 4K resolutions. Or I hope I am wrong. If someone knows how to run 4K video with omxplayer, that would be a gem. all the best
