### ISSUE TITLE
network is unreachable

### ISSUE THREAD

**Issue by burtonworldart** [turingmachine/omxplayer-sync#37]
Cool software,  thank you.
Is wifi dongle and LAN required for this to run?
when I play master (sudo omxplayer-sync -muv /home.pi/videos/syntest.mp4)  won't work unless I am connected to my home wifi network. Will it run point to point via RJ45 alone?
Does it require RJ45 crossover cables?

Thanks for your help!

**Comment by Francesc116** [comment]
I tested the LAN. It works too under Wheezy.

Pi 1
$ sudo nano /etc/network/interfaces
Delete iface eth0 inet dhcp. In fact, all the lines with eth0 info
Add

iface eth0 inet static
address 192.168.0.1
netmask 255.255.255.0
gateway 192.168.0.254

Pi 2, the same but
iface eth0 inet static
address 192.168.0.2
netmask 255.255.255.0
gateway 192.168.0.254

It works to me. Maybe it helps.

**Comment by burtonworldart** [comment]
Ah Ha!  Thanks a lot!  I was missing the gateway 192.168.0.254.  Still encountering major deviation in sync across rj45 cable but at least both pis are on the same network.

**Comment by burtonworldart** [comment]
I'm calling it quits on this software,  Thanks for your help Francesc116!  Can't solve the rising deviation problem even with good network connection. Might be hardware but running same device and same class 6 sd cards. Tested on 3 sets of cards and same deviation error exists. Who knows..  

Hope you solve the dbus issue:  I had that error and solved for Wheezy with sudo apt-get install python-dbus directly from the /home/pi/Videos directory.  Make sure you "apt-get autoremove" after you install. (it gets rid of an extra file).

Wish the developers of this software would chime in more.   Feel like you guys either dropped this mic on this one or aren't interested in the novice user.

Good luck

**Comment by turingmachine** [comment]
@burtonworldart what exactly is your issue you have with the software? The title of this thread reads " network is unreachable". Do you still have network connectivity problem? If not please let the thread know so this issue can be closed. If you encounter other problems, please open a separate issue for each problem. This common netiquette in open source communities.

Below some guidelines that explain what I mean:

Be precise: don’t wander around and go straight to the point, describing as precisely as possible what’s happening
Be clear: explain how to reproduce the problem, step by step, so others can reproduce the bug
Be economic: provide the minimum amount of information needed to understand what’s happening
Be clean: report only one problem per issue so we can track individual issues
Be curious: has it been asked before? is it really a bug? Google is your friend!

http://www.kurento.org/blog/kurento-issue-tracker-guidelines
