### ISSUE TITLE
Keyboard control

### ISSUE THREAD

**Issue by chuco61** [turingmachine/omxplayer-sync#38]
Does anyone have a functional keyboard controls working on the omxplayer-sync?

I have my master finally working and am planning on connecting my slaves via a ethernet switch tonight.

**Comment by turingmachine** [comment]
Unfortunately keyboard inputs are not forwarded to omxplayer. This could be implemented as a feature.

**Comment by magdesign** [comment]
dBus controls work pretty well, but keep in mind that the pause function via dBus control works only for 4 seconds, then omxplayer-sync tries to resync.

**Comment by chuco61** [comment]
Ok i will look into this, thank you both for the reply. Currently I have another thread open trying to work through a dbus error on Jessie.
