### ISSUE TITLE
Black Screen at the end 

### ISSUE THREAD

**Issue by raspdev** [turingmachine/omxplayer-sync#39]
Hi everyone and thank by this amaizing effort. 

I used omxplayer-sync months ago, and I couldn´t avoid to show the terminal screen in each loop. The question is, is it possible to put a black screen when a new sync starts? Sometimes the videos are very short, so when the video finish get the terminal screen with the commands and it not very pretty. Please if there is any way to implement a black screen I´m very interested. 

Thank very much.

**Comment by YohannLYD** [comment]
The trick I use to avoid seeing the console at the end of the loop is to run the command _tvservice -p_ which refreshes the screen to the preferred resolution set in /boot/config.txt.
Then the console should disappear and you can run any instance of omxplayer/omxplayer-sync without seeing the console.

**Comment by raspdev** [comment]
Hi, thanks for you soon reply.  I´m going to try you trick.

**Comment by peterjosvai** [comment]
I just tried "-b" ... like with the normal omxplayer, and it works...

**Comment by zhiwan** [comment]
Hello,

Just to confirm, to use tvservice -p, would the code look like this?

omxplayer-sync -muv synctest.mp4 tvservice -p?

I still see the console with this. I also put tvservice -p in /boot/config.txt and that didn't work either. I also tried "-b":

omxplayer-sync -b -muv synctest.mp4

That didn't work either. Can someone clarify this?

**Comment by magdesign** [comment]
to clear screen after boot you can try:

sudo sh -c "TERM0linux setterm -foreground black >/dev/tty0"
sudo sh -c "TERM0linux setterm -clear all >/dev/tty0"

then start omxplayer-sync: omxplayer-sync -b -mu synctest.mp4

don't write the -v, since this is verbose mode and will give you an output to the console....
