### ISSUE TITLE
Blacking Out screen

### ISSUE THREAD

**Issue by chuco61** [turingmachine/omxplayer-sync#41]
I have uploaded a problem with my omxplayer-sync install.

I do have it successfully syncing across my master and slave. Can't wait to get it working with the rest of my pi's.

[](https://www.youtube.com/watch?v=UyWWQI-Lk18&feature=youtu.be)

What are some solutions to this problem? I am using a RPi3 and Jessie

**Comment by magdesign** [comment]
Please describe exactly what your question is and a way that I can reproduce it.
