### ISSUE TITLE
option --win doesn't work, can it be used? (just asking)

### ISSUE THREAD

**Issue by peterjosvai** [turingmachine/omxplayer-sync#42]
hi, 
thanks for your work, it is awesome!

I just realized that one can add "extra" options (other than what your modified omxplayer version's manual lists) I could add -b, for example... 
then I tried --win "0 0 1920 1080" , and it didn't ... the playing didn't start

I'm not complaining :) omxplayer-sync works great...
just asking if the --win options could be activated in any way

thank you

Peter

**Comment by peterjosvai** [comment]
okay, I found the answer: no :)


quote from the script:

> for argument in arguments:
            if argument.startswith('-'):
                self.omxplayer_options.append(argument)
            else:
                self.playlist.append(argument)

**Comment by peterjosvai** [comment]
okay, sorry for the silly question :)

of course one can add this in the python file:

>  self.omxplayer_options.append('--win "0 0 1920 1080"')


and: THANKS again for omxplayer-sync :)

**Comment by flycrshish** [comment]
sorry
try to edit this line in  /usr/bin/omxplayer-sync 
self.omxplayer_options.append('--win "0 0 1920 1080"') 
run
omxplayer-sync -luv /home/pi/playfile.avi
but --win setting is not work ,  am i lost some thing ?
( omxplayer --win "0 0 1920 1080" /home/pi/playfile.avi     is work)

**Comment by flycrshish** [comment]
add -s is work ,no question now.
 omxplayer-sync -luv /home/pi/playfile.avi -s

**Comment by ADSPL** [comment]
@peterjosvai @flycrshish Did you guys able to use --win "0 0 1920 1080" ?
I am trying to do same, but could not archive it.
Please help
