### ISSUE TITLE
Sync changes every loop

### ISSUE THREAD

**Issue by raspdev** [turingmachine/omxplayer-sync#43]
Hi everyone, 

I have a problem with the sync. When I start the sync, for example first the Master and them the slave the sync use to work perfect but when the video finish and it start again there is a difference of frames. It´s very strange, because sometime at the begining sync perfect but sometimes not, I´m using the same video. I tried to adjust the sensibility in the conf file but it didn´t not work. 

When the loop starts the sync needs 13 sencods to sync the slave with the master, and I told you up sometimes sync perfect after this 13 seconds and sometimes there are some frames of difference. 

I tried with different videos, with a different switch, with a direct ethernet cable, etc. 

My config is:

2 X Raspberry Pi 2 
Conection between direct ethernet link. 

Best Regards.

**Comment by magdesign** [comment]
There is a new version of the script in which this behaviour should be fixed.

Uninstall the old version and the old omxplayer, install the new ones and report back.
