### ISSUE TITLE
How to quit playback?

### ISSUE THREAD

**Issue by demmaone** [turingmachine/omxplayer-sync#44]
Hello, I`m testing this version via ssh and I can´t find a way to quit the player. I tried opening a Terminal windows in the Raspberry and type "killall omx-player" and the command kill it but less than a second after it starts again. I just want to quit to change videos and continue testing.
Thanks in advance.

**Comment by turingmachine** [comment]
You only kill the omxplayer instance that omxplayer-sync spawned and thus it will be respawned if killed. You need to kill both omxplayer-sync and omxplayer, e.g. `killall omxplayer-sync omxplayer`.

**Comment by tsantor** [comment]
I have the same issue, but when I try that command the process is not found.

```
$ killall omxplayer-sync omxplayer
omxplayer-sync: no process found
```

**Comment by spleeen1** [comment]
I am also looking for an answer to this. Neither q, nor ctrl+C seems to do the trick. if I do 
$ killall omxplayer-sync omxplayer i also get
omxplayer-sync: no process found
any help would be great!
