### ISSUE TITLE
Raspberry Pi 3 compatibility

### ISSUE THREAD

**Issue by pennanhuo** [turingmachine/omxplayer-sync#46]
I'm trying to get this to work on Pi 3. I'm a total noob but I think I have all the parts mentioned in the installation guide.

The only this I can notice, is that my rasbian cannot find these "ln -sf /lib/arm-linux-gnueabihf/libpcre.so.3 /lib/arm-linux-gnueabihf/libpcre.so.1"

Could anyone give me a suggestion how to fix it?

**Comment by turingmachine** [comment]
Do you have any other libpcre version available?
Please paste the output of the following command:
``
find /lib | grep libpcre
```

**Comment by pennanhuo** [comment]
Got it to work with a fresh install.
