### ISSUE TITLE
WARNING: omxplayer did not start. Try to test with 'omxplayer -s OPTIONS'

### ISSUE THREAD

**Issue by zhiwan** [turingmachine/omxplayer-sync#50]
I currently am trying to start up omxplayer-sync upon start up. I created a bash script (omx-sync.sh) with the code: 

/usr/bin/omxplayer-sync -mu -o both /home/pi/video.mp4
for master and: 

/usr/bin/omxplayer-sync -lu -o both /home/pi/video.mp4
for slave. 

I then put in /etc/profile I added at the very bottom:

. /home/pi/omx-sync.sh &

With this setup, sometimes autoplay upon startup works for video files of smaller bitrates and lower quality, but sometimes I see the error:

WARNING: omxplayer did not start. Try to test with 'omxplayer -s OPTIONS'

I end up either 'sudo reboot' or unplugging/replugging the pi and usually after two or three tries it works. I also exported the same video with varying bitrates levels and distributed the videos on the master and slaves. I noticed that as the video quality and file size goes up, I begin to see the error code on the slaves more frequently.

If I type the code in the terminal (omxplayer-sync -lu video.mp4), all videos work, including the higher bitrate videos. Does anyone else run into this issue and have any idea why the error code happens?

**Comment by mrpropre** [comment]
Same here, but it happens when I type it in terminal, with many 1080p video files.
Sometimes I have a green screen on my slaves and I need to reboot.

I tried to put the autostart .sh script in my rc.local file but I see that the slaves aren't starting and display "WARNING: current master file 'myfile.mp4' is unavailable". Where did you called the script?

**Comment by magdesign** [comment]
@zhiwan: i still do it the oldschool way and put the lines for autostart into 

`/etc/rc.local`

 and this works fine...

**Comment by zhiwan** [comment]
@magdesign I have done it that way but in testing different video files, I find with /etc/rc.local, the terminal never seems to load and I cannot ctr+c to get out of omxplayer. I end up having to ssh in from another computer and comment out the line in rc.local to use the terminal. Is that what you do if you need to switch out a video file or do you do something differently?

**Comment by magdesign** [comment]
I'm running a webserver and have full control via a webbrowser to change video file etc.
Get it here: https://github.com/magdesign/PocketVJ-CP-v3

I also added a variable to kill omxplayer, so i can type: omxkill and all omxplayer get killed (killall -9 /usr/bin/omxplyer.bin)

**Comment by mrpropre** [comment]
I still have the Warning message with some files... and I need to start them a second time so they they can be read by omxplayer.

here is the codec info of the non working one...

![capture d ecran 2016-09-23 a 18 38 51](https://cloud.githubusercontent.com/assets/5449719/18793906/2fc72f62-81bd-11e6-9e0d-6b38aa4c3e44.png)


And here is the working one:

![capture d ecran 2016-09-23 a 18 32 11](https://cloud.githubusercontent.com/assets/5449719/18793911/38e41b0a-81bd-11e6-8dc1-cae8802f644f.png)


Can you tell me what's wrong? could it be the file size? the duration? Thanks for any hint!

**Comment by turingmachine** [comment]
It is possible that omxplayer takes longer than usual to start on your system. There is a hard coded value that defines the amount of time that omxplayer-sync waits before it tries to interface with omxplayer on dbus. You could try to raise value found on line 85 of the omxplayer-syn file:
https://github.com/turingmachine/omxplayer-sync/blob/master/omxplayer-sync#L85

**Comment by mrpropre** [comment]
Thanx, changing the value to 20 fixed the problem for me.

**Comment by zhiwan** [comment]
I also raised that number and it seemed to fix it.
