### ISSUE TITLE
Master and slave stop playing after some time

### ISSUE THREAD

**Issue by mrpropre** [turingmachine/omxplayer-sync#51]
Since the beginning, I have this problem, both player stop and the master/slave are not sending  position information anymore. Here is the video information:

Format                                   : MPEG-4
Format profile                           : QuickTime
Codec ID                                 : qt  
File size                                : 2.32 GiB
Duration                                 : 32mn 13s
Overall bit rate mode                    : Variable
Overall bit rate                         : 10.3 Mbps
Encoded date                             : UTC 2016-09-28 05:54:39
Tagged date                              : UTC 2016-09-28 07:15:43
Writing library                          : Apple QuickTime
©TIM                                     : 00:00:00:00
©TSC                                     : 25
©TSZ                                     : 1

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Main@L4.0
Format settings, CABAC                   : No
Format settings, ReFrames                : 2 frames
Format settings, GOP                     : N=1
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 32mn 13s
Bit rate mode                            : Variable
Bit rate                                 : 9 975 Kbps
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.192
Stream size                              : 2.25 GiB (97%)
Language                                 : English
Encoded date                             : UTC 2016-09-28 05:54:39
Tagged date                              : UTC 2016-09-28 07:15:43
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : 40
Duration                                 : 32mn 13s
Source duration                          : 32mn 13s
Bit rate mode                            : Constant
Bit rate                                 : 320 Kbps
Nominal bit rate                         : 128 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Compression mode                         : Lossy
Stream size                              : 73.7 MiB (3%)
Source stream size                       : 73.8 MiB (3%)
Language                                 : English
Encoded date                             : UTC 2016-09-28 05:54:39
Tagged date                              : UTC 2016-09-28 07:15:43

**Comment by zhiwan** [comment]
I'm also running into this issue. For me, it seems omxplayer-sync simply stops. 

I will run overnight video tests and at some point, one pi will stop playing. Usually the screen will be black when I see it. If I press any key on a keyboard, I will see the command line 

pi@raspberrypi ~ $

Which means the player stopped and the screen went into screen saver from no input. I don't seen any error, so I don't know why it's stopping. Has anyone else come across this?

**Comment by magdesign** [comment]
Turn off all screensaver, power saving etc. modes... 
you have to do this as pi user and also as root user.

**Comment by zhiwan** [comment]
I will try that but it seems that the screensaver/powersaving mode is occurring because omxplayer stopped, not because the screensaver is overriding the video, unless you think this is the case? It's not like when I hit a key on the keyboard that the screensaver then goes back to the video but instead I see the command line...

**Comment by magdesign** [comment]
Its definitely not a problem of omxplayer-sync... its running since days here...

**Comment by zhiwan** [comment]
Okay. So is the powersaving mode turning off omxplayer?

This is what I found: 

https://www.bitpi.co/2015/02/14/prevent-raspberry-pi-from-sleeping/

Is this the steps you would recommend? I am also a bit confused by your comment about doing both as a pi user and root. Can you clarify?

**Comment by zhiwan** [comment]
I just turned off the powersaving mode and the video still stopped at one point. I will come to the video and see the command line. I'm not quite sure what is causing it...

**Comment by zhiwan** [comment]
At this point, I don't know if it's omxplayer-sync or my video, so I ended up writing a bashscript that checks that omxplayer-sync is running, and if not, it will reset it. It doesn't seem elegant but there doesn't seem to be anything else that has been suggested. 

#!/bin/sh

SERVICE='omxplayer-sync'
while true; do
   if ps ax | grep -v grep | grep $SERVICE > /dev/null
   then
      echo "running" 
   else
      /usr/bin/omxplayer-sync -mu -o both /home/pi/video.mp4
   fi
done
