### ISSUE TITLE
other player support

### ISSUE THREAD

**Issue by morfeus2** [turingmachine/omxplayer-sync#56]
Are there any plans to support other players?
I mean to sync omxplayer (slave) running on a raspberry with for example mplayer (master) running on a PC.

**Comment by turingmachine** [comment]
No Plans. omxplayer only runs on hardware that supports https://en.wikipedia.org/wiki/OpenMAX. You could although add support for the omxplayer-sync network sync protocol to other players. Pull requests are welcome.
