### ISSUE TITLE
Simple black background command addition ?

### ISSUE THREAD

**Issue by renoproc** [turingmachine/omxplayer-sync#58]
Hi, 
for my own usage I've added a simple black background command in omxplayer-sync, -b option of omxplayer. A really simple but I think usefull thing. Could it be integrated in the next commit ?

after `def run(self):` line 137, added 
`p.add_option('--black', '-b', action='store_true')`

after `self.omxplayer_options.append('--no-osd')` line 167, added 
`if self.options.black: 
            self.omxplayer_options.append('-b')`

Many thanks !

**Comment by turingmachine** [comment]
As a matter of fact, omxplayer-sync already passes all options that omxplay-sync doesn't know of to omxplayer. So you could already run omxplayer-sync -b with the current version. Please not that this doesn't work options that expect an argument.

**Comment by vanDemonian** [comment]
Thanks. This is great to know. Perhaps it could be added to the read Me?

**Comment by turingmachine** [comment]
Yes that would be great. Pull requests are welcome!
