### ISSUE TITLE
Auto-Start

### ISSUE THREAD

**Issue by afarret** [turingmachine/omxplayer-sync#61]
Hey,
Thanks for putting this together. Have you found a way to make this auto start? I have tried a few ways without success; however, running the script and Execute in Terminal works perfect. Many thanks.

**Comment by achterbahn** [comment]
@afarret Find here a solution that worked quite well for me.
[OMXPLAYER](https://www.raspberrypi.org/forums/viewtopic.php?t=175434&p=1119841)

**Comment by turingmachine** [comment]
Yes, starting it via /etc/rc.local is a solution.
