### ISSUE TITLE
Update Question

### ISSUE THREAD

**Issue by chuco61** [turingmachine/omxplayer-sync#63]
I've just realized that I am using an old version of omxplayer-sync, since I have all my slaves and master currently configured and communicating ... what is the best way to update to the new version of omxplayer-sync, rather than going through all the installation steps again?

Thanks

**Comment by turingmachine** [comment]
Replace /usr/bin/omxplayer-sync with the newest version from Github and install the latest version of omxplayer from here http://omxplayer.sconde.net/.

**Comment by chuco61** [comment]
Thank you! essentially I would run these two commands? From your tutorial.
wget http://omxplayer.sconde.net/builds/omxplayer_0.3.7~git20160713~66f9076_armhf.deb
dpkg -i omxplayer_0.3.7~git20160713~66f9076_armhf.deb

I dont need to uninstall the previous version?
How can I check to see if by chance, I am actually running 0.3.7? I doubt my version is current, but I would like to verify.

**Comment by turingmachine** [comment]
No the previous version will be updated.
You can check with ```dpkg -l | grep omxplayer```.

**Comment by chuco61** [comment]
awesome, thank you!! so those two commands, and I should be good to go

**Comment by magdesign** [comment]
Why don't you just try it and open an issue if it fails...?

**Comment by chuco61** [comment]
Currently, there is a pause and desktop shows after the video is done. So I am assuming that the seamless loop is not current in my version. I am asking now how to do all of this because I am at work and want to know the process before I get home, otherwise, I'll have no idea where to start. Thanks everyone for the direction.

**Comment by turingmachine** [comment]
@chuco61 If you have another questions or issue, please open another ticket for that. Is the issue with the updates resolved for you?
