### ISSUE TITLE
option -u loop 

### ISSUE THREAD

**Issue by magdesign** [turingmachine/omxplayer-sync#64]
Just figured out this issue since the new gapless script:

When starting `omxplayer-sync` without the `-u` flag it does not loop which is correct
but 
when starting `omxplayer-sync -o local`  it loops but it should not!
(-o local stands for the audio output)

There must be an issue in forwarding the flags.
(when I switch to the old script, everything works.

**Comment by turingmachine** [comment]
Ds Problem isch ja huere simpu:

Im momänt gäbe mer --loop em omxplayer witer wenns nur 1 file ir  
playlist het. Das darfsch aber nur mache wenn dr user ou -u het  
mitgäh, das heisst wener üerhoupt wot loope...


aus dr fix isch:


stattt:
         if len(self.playlist) == 1:
             self.omxplayer_options.append("--loop")
so:
         if self.options.loop and len(self.playlist) == 1:
             self.omxplayer_options.append("--loop")


bi grad dr neu kompi am ufsetze. villech wosches ja du grad hurti commite.

cheerio


Zitat von magdesign <notifications@github.com>:

> Just figured out this issue since the new gapless script:
>
> When starting `omxplayer-sync` without the `-u` flag it does not loop
> but
> when starting `omxplayer-sync -o local`  it loops but it should not!
> (-o local stands for the audio output)
>
> There must be an issue in forwarding the flags.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/turingmachine/omxplayer-sync/issues/64


-- 
Simon Josi > Systems-Engineer > Software-Developer
YOKTO Engineering > http://yokto.net > me@yokto.net

**Comment by turingmachine** [comment]
fixed in 4d43877.
