### ISSUE TITLE
Looping

### ISSUE THREAD

**Issue by aaist** [turingmachine/omxplayer-sync#65]
Hello,

I am able to get this working and have a perfect sync going across multiple pis. Unfortunately however, despite not using the 'loop' function in my code, the video seems to loop endlessly.

How do I command it to just play once and then end/close?

I am using the following as a test: 
omxplayer-sync -luv --no-osd synctest.mp4
omxplayer-sync -muv --no-osd synctest.mp4

Thank you.

**Comment by magdesign** [comment]
As you could read in theREADME, the -u option stands for loop.

In your case, your command would look like: `omxplayer-sync -l  synctest.mp4`

Keep in mind that there is a bug when defining the audio device:  https://github.com/turingmachine/omxplayer-sync/issues/64

**Comment by aaist** [comment]
Hi magdesign.

I am aware that the -u option is for looping. My question was that my command is not using the -u function - I do not want the video to loop, and even without the -u, it is looping by default.

**Comment by magdesign** [comment]
did you start master and slave like this: 

`omxplayer-sync -l synctest.mp4`
`omxplayer-sync -m synctest.mp4`

as mentioned before there is an issue when sending other flags like:` -o local `
`--no-osd` is not necessary
Do you have a newer build of omxplayer?

**Comment by aaist** [comment]
Yes even with that it loops in exactly the same way. I have installed the latest version available without any modification from the instructions listed.

It is working as I want but I don't want it to keep looping. Is there a way to turn it off? I'd want to be able to turn it on by using -u but not for it to be on by default.

**Comment by magdesign** [comment]
Try using the older version of the script.
I think since the seamless update we have a bug in the code...

**Comment by turingmachine** [comment]
Yes try the commit before the last one. I'll look into it this evening.

**Comment by aaist** [comment]
Thank you both. Could you please point me to the old one to try?

**Comment by turingmachine** [comment]
Fixed in 4d43877.

**Comment by aaist** [comment]
Thank you so much, works perfectly for me now :)
