### ISSUE TITLE
omxplayer-sync codec behaviour

### ISSUE THREAD

**Issue by magdesign** [turingmachine/omxplayer-sync#67]
Just figured out a strange behavior:
I have a h264 encoded video which plays well with omxplayer.
But when I want to play it with omxplayer-sync, it does not start and sends me:
**WARNING: omxplayer did not start. Try to test with `omxplayer -s OPTIONS`**

Is omxplayer-sync referencing to some other codec libraries ?

I want to know why the movie plays with omxplayer and does not with omxplayer-sync.
Thanks for any (debugging-) inputs.

**Comment by DSPeelJ** [comment]
I had that issue as well.  You need to add more to the sleep setting on line 85.  This is addressed in an earlier issue.  Increasing the value took care of the problem for me.
 
 def initialize(self):
        sleep(2) # wait for omxplayer to appear on dbus
        return self._get_dbus_interface()
I changed mine to 10 instead of 2

**Comment by magdesign** [comment]
Thanks for your fast feedback, this is helping a lot!
I am just trying it out with the sleep change you mentioned.
If there is no impact in syncing and playlist syncing, I will push it to the code.
Are you aware of any strange behaviors after adding sleep 10 ?

**Comment by DSPeelJ** [comment]
No impact that I've seen.  I made sure all the players are set to the same values.

**Comment by magdesign** [comment]
Thanks for your input.
Tested and seems to work stable. 
Updated the script.
