### ISSUE TITLE
HDMI with raspberry 7" Display connected to DSI

### ISSUE THREAD

**Issue by nils1976** [turingmachine/omxplayer-sync#70]
I am wondering if it is possible to play the output to HDMI not to raspitouch? omxplayer has the option --display 5 which works fine... Is there a easy way to put that into the script? My programming skills are awfull so any idea would be fine

Thanks for help Nils

**Comment by turingmachine** [comment]
Below line 164 you could add:
```
self.omxplayer_options.append('--display 5')
```

**Comment by nils1976** [comment]
I will give that a try!
Thanks for the reply

Best Regards Nils
