### ISSUE TITLE
Instructions only work for Raspbian Jessie, not Stretch

### ISSUE THREAD

**Issue by pagaille** [turingmachine/omxplayer-sync#71]
Two issues related to Raspbian Stretch :

1. At the time of writing, the latest omxplayer found on doesn't install itself on Raspbian Stretch because of an unmet dependency (libssl1.0.0). I didn't find an easy workaround.

2. Installing the default packaged version of omxplayer (apt-get install omxplayer) is possible and works, but there is an additional issue regarding network connectivity (and therefore synchronisation) when autostarted, wether through systemctl or by adding a line to /etc/rc.local. Looks like the master is not able to broadcast the timecode information, even while the network is up.

Just to save others time, I lost a bunch of it on this :-) --> Use Raspbian Jessie :-)

Anyway thanks for that nice work !

**Comment by turingmachine** [comment]
What version was installed on Stretch? Do I understand correctly, that you resolved the autostart issue by switching to Jessie? Sync did work with manual startup on sretch?

**Comment by pagaille** [comment]
- Latest versions of your app and omxplayer
- Autostart issue was indeed 'solved' by switching to Jessie
- Sync did work perfectly when started manually on stretch

**Comment by turingmachine** [comment]
The version in numbers, e.g. 0.3.7.

**Comment by pagaille** [comment]
omxplayer_0.3.7~git20170130~62fb580_armhf.deb

**Comment by pagaille** [comment]
I opened a case on it's GitHub repo as well.

**Comment by turingmachine** [comment]
0.3.7 was the version on stretch? Well if it works when started manually it is most probably not an issue with omxplayer itself.

**Comment by pagaille** [comment]
I move the second issue to another thread.

**Comment by chiguire** [comment]
Consider that Raspbian Jessie is not supported by Raspberry Pi 3 Model B+. There are ways to make it work on the Internet, but I couldn't make it work. I'm stuck with Stretch for this model.

**Comment by magdesign** [comment]
Here is the description what you have to do to make it Jessie work on RPi3 B+:

https://github.com/magdesign/PocketVJ-CP-v3/issues/53
