### ISSUE TITLE
raspbian : master doesn't broadcast timecode when configured as a DHCP server

### ISSUE THREAD

**Issue by pagaille** [turingmachine/omxplayer-sync#73]
If those three conditions are met :

- master role
- DHCP server
- autostarted through rc.local or systemd

then omxplayer-sync doesn't broadcast timecodes

I ended up configuring one pi as DHCP server (and slave) and another one as master (and DHCP client). Others are slave and DHCP client.

**Comment by chiguire** [comment]
I happen to have the same problem (reading from issue #71), except:

* Statically configured network
* Slave doesn't connect
* Autostarted from lxsession

When I start a master and a slave (I only need two screens) manually, it works fine. If I start them from lxsession/.../autostart it won't work (only the master starts).
