### ISSUE TITLE
Looping video

### ISSUE THREAD

**Issue by JThau** [turingmachine/omxplayer-sync#74]
Hi there,

First of all thanks for this awesome syncing script!

For some reason I can't seem to get the seamless loop function working, it'll always close the player and start up a new one, as if it's not utilizing or parsing the loop option to omxplayer. I've followed the readme to end, but somehow can't seem to get the looping option working. Did I mistake how it loops ? Is it supposed to close the program, open a new one and make the loop like that ?

My options parsed is omxplayer-sync -muvo hdmi /home/pi/Desktop/movie.mov

I use a Raspberry Pi 3 Model B+
I use the latest commit from omxplayer-sync
I use the omxplayer_0.3.7~git20160713~66f9076_armhf.deb build from sconde.net
Thanks in advance

**Comment by turingmachine** [comment]
Does semless look work with the omxplayer you are using? Try
```omxplayer --loop /home/pi/Desktop/movie.mov```

**Comment by magdesign** [comment]
Make sure that there is only one video file in the folder and nothing more, then it works.

**Comment by JThau** [comment]
There's only one file, and that's the movie, nothing else. It's not seamlessly looping, it feels like it's closing the player down and then starting a new one up.
