### ISSUE TITLE
Question & option added

### ISSUE THREAD

**Issue by renoproc** [turingmachine/omxplayer-sync#75]
Hi, just to ask if it's possible to add the --black option (I made it on my own [here](https://gist.github.com/renoproc/de081a92dfa3f9269586c1a6ff8fe59c/revisions)), in some cases this option is useful.

And a question : is it possible to enable a namedpipe option on omxplayer-sync ?
As the omxplayer commandline  : omxplayer -options /path/to/video/* < /tmp/omxPipe > /dev/null 2>&1 &
This could be useful to allow commands using the namedpipe to send keypressed instructions to omxplayer, like p/space to pause/resume, - to decrease volume, +/= to increase volume...

**Comment by magdesign** [comment]
Pause, Resume and Volume can be controlled via DBus commands.
I think we disabled key commands because it somehow disturbed the sync, but I am not sure.

**Comment by renoproc** [comment]
Yes I saw it (after), there is an issue discussion about key bindings : [https://github.com/turingmachine/omxplayer-sync/issues/62](https://github.com/turingmachine/omxplayer-sync/issues/62)

But I think that could be nice to add the black background (--black -b) option.
If, as I do, someone works with another script, there are some text shown on the screens and the black option helps to hide it.

Also magdesign, I was inspired by pocketvj project (thanks for it), but because of my work with art students, we don't need all the interface and we made a scrapy script using socat/udp broadcast messages and [Flirc](https://flirc.tv) dongle to be able to use a TV remote control. Which works like a charm.

**Comment by pagaille** [comment]
The b (black) option is implemented ASFAIK. Just launch the master with `/usr/bin/omxplayer-sync -mub  --no-osd ~/video.mp4`

**Comment by renoproc** [comment]
As I saw there is no b option :
 ```p = PassThroughOptionParser()
        p.add_option('--master', '-m', action='store_true')
        p.add_option('--slave', '-l', action='store_true')
        p.add_option('--destination', '-x', default='255.255.255.255')
        p.add_option('--loop', '-u', action='store_true')
        p.add_option('--verbose', '-v', action='store_true')
        p.add_option('--adev', '-o', default='both')
 self.options, arguments = p.parse_args()
```

But I didn't see these lines, which perhaps give the ability to pass new options to omxplayer (I'm not a pythoner, so I'm not sure)
```for argument in arguments:
            if argument.startswith('-'):
                self.omxplayer_options.append(argument)
else:
```
