### ISSUE TITLE
Syncing different video files

### ISSUE THREAD

**Issue by NeoNatorX** [turingmachine/omxplayer-sync#76]
Hi not an issue just a quick question

Can omxplayer-sync  sync different videos? 
As in videos intended to be played side by side but are not the same video file
eg an animated video of a red ball bouncing and another video of a blue ball bouncing

If it can what happens if the videos are different lengths?

Thanks for your help

**Comment by DSPeelJ** [comment]
You can run different files as long as you name them all the same. I'm running 24 different files, all with the same name and encoded identically and haven't had any issues. They are all the same length though. Perhaps of the master is the longest one...  They will all follow the master so if they are longer, they'll restart when the master does.

**Comment by NeoNatorX** [comment]
Thanks for the quick response. Perfect! Ill have to look into doing it with different lengths hopefully it works :) Thanks for help! :D
