### ISSUE TITLE
Jump to different Position

### ISSUE THREAD

**Issue by MakeProjects** [turingmachine/omxplayer-sync#77]
Hi, 

I would like to congratulate you for the project, It is fantastic. I need to change or jump to different position during the sync using the GPIO with a sensor. My project has two projectors sync. 

Is it possible to jump to different position during the sync without problems?

Thanks

**Comment by DSPeelJ** [comment]
Hi,
It feels like that wouldn't work as the slaved player would take a bit to
catch up but others may know better than I.  Can you outline your project
in a little more depth?  There may be other ways to achieve what you want.

Thanks,
John

**Comment by MakeProjects** [comment]
Hi, 

Yes of course. I need to interact with videos, when something happens maybe someone press a button or be detected by a sensor the video should be change. I´ve thought in use two different videos and start different syncs instances with a python script but I´m sure that I´m going to get a black screens when switch the syncs, and It is a big problem. 

I´m using omxplayer-wrapper in a single TV`s or Projectors and  to jump to different position in the video and It works perfect, no delays, no black screens, etc. because I´m very intererested to know that it is possible with the sync too. 

Thanks,

David.

**Comment by turingmachine** [comment]
You could jump to any position of the master by dbus commands and the slaves will follow.
