### ISSUE TITLE
libssl1.0.0 is not installed

### ISSUE THREAD

**Issue by MennoBroere** [turingmachine/omxplayer-sync#80]
Hi,

I'm trying to install OMXplayer-Sync on a fresh Raspberry Po Model 3b+ running the latest version of Streth.  But when running:

dpkg -i omxplayer_0.3.7~git20170130~62fb580_armhf.deb

I got this errors:

dpkg: dependency problems prevent configuration of omxplayer:
 omxplayer depends on libssl1.0.0; however:
  Package libssl1.0.0 is not installed.

dpkg: error processing package omxplayer (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.7.6.1-2) ...
Errors were encountered while processing:
 omxplayer

It looks like libssl is not included in Stretch. But running Jessie on a Model 3B+ ins't possible either. 

How could i fix this?

Thanks!

**Comment by magdesign** [comment]
We never tested it on Stretch so far.
Did you try to install libssl1.0.0 manually from here: https://packages.debian.org/jessie/libssl1.0.0

**Comment by stroith** [comment]
> This does get me further but i'm not able to play any files:
> 
> root@raspberrypi:/home/pi# omxplayer-sync -muv synctest.mp4
> WARNING: dbus connection could not be established
> org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer2.omxplayer was not provided by any .service files
> WARNING: omxplayer did not start. Try to test with omxplayer -s OPTIONS
> root@raspberrypi:/home/pi#

I'm having the same issue

**Comment by belowlight** [comment]
I was able to resolve this error by installing the latest libssl using:
`apt-get install libssl1.0.2`

This installs and then grumbles about omxplayer being broken, which you can fix using the command it suggests as a second step:
`apt --fix-broken install`

Works fine for me after those two steps run on both master + slave RPi's.

**Comment by DSPeelJ** [comment]
Thanks for the input!

**Comment by 3mrrrx** [comment]
i am have the same issue..

apt-get install libssl1.0.2

did not help!

**Comment by 3mrrrx** [comment]
i think its an operating system issue, as  the Raspian Stretch does  not have libssl1.0.0 installed.

on my pi3 b+ i can only install libssl1.0.2 not libssl1.0.0 

i also installed libssl-dev

i tried creating symbolic links of both  libssl1.0.2 and libssl-dev to libssl1.0.0 

still did not help!

sad that code can not run on current systems.

**Comment by pagaille** [comment]
In my installation notes back in april 2018 I wrote "!!! omxplayer currently only installs itself on Jessie (not Stretch) because of a unmet dependency  —> libssl1.0.0"

**Comment by belowlight** [comment]
Just on the off-chance, you might consider trying to install the latest libssl beta using:

apt-get install libssl1.1.1

**Comment by Mediensysteme** [comment]
The following commands worked for me:
```
sudo su  
apt-get install libghc-these-prof 
apt-get install libghc-terminal-size-prof
apt-get install libglib2.0-dev
apt-get install libgtk2.0-dev
apt-get install --reinstall python-gi
apt-get install ffmpeg
apt-get remove omxplayer
rm -rf /usr/bin/omxplayer /usr/bin/omxplayer.bin /usr/lib/omxplayer
apt-get install libpcre3 fonts-freefont-ttf fbset libssh-4 python3-dbus
wget http://omxplayer.sconde.net/builds/omxplayer_0.3.7~git20170130~62fb580_armhf.deb
dpkg -i omxplayer_0.3.7~git20170130~62fb580_armhf.deb
wget -O /usr/bin/omxplayer-sync https://github.com/turingmachine/omxplayer-sync/raw/master/omxplayer-sync
chmod 0755 /usr/bin/omxplayer-sync
chmod 0755 /usr/bin/omxplayer
apt --fix-broken install
apt-get install libpcre3
apt --fix-broken install
wget https://github.com/turingmachine/omxplayer-sync/raw/master/synctest.mp4```

**Comment by Mediensysteme** [comment]
The following commands worked for me:
```
sudo su
apt-get update
apt-get upgrade
apt-get install libghc-these-prof
apt-get install libghc-terminal-size-prof
apt-get install libglib2.0-dev
apt-get install libgtk2.0-dev
apt-get install --reinstall python-gi
apt-get install ffmpeg
apt-get remove omxplayer
rm -rf /usr/bin/omxplayer /usr/bin/omxplayer.bin /usr/lib/omxplayer
apt-get install libpcre3 fonts-freefont-ttf fbset libssh-4 python3-dbus
wget http://omxplayer.sconde.net/builds/omxplayer_0.3.7~git20170130~62fb580_armhf.deb
dpkg -i omxplayer_0.3.7~git20170130~62fb580_armhf.deb
wget -O /usr/bin/omxplayer-sync https://github.com/turingmachine/omxplayer-sync/raw/master/omxplayer-sync
chmod 0755 /usr/bin/omxplayer-sync
chmod 0755 /usr/bin/omxplayer
apt --fix-broken install
apt-get install libpcre3
apt --fix-broken install
wget https://github.com/turingmachine/omxplayer-sync/raw/master/synctest.mp4
```

running on RaspberryPi 3 B+ 2017 with 2018-11-13-raspbian-stretch
