### ISSUE TITLE
Anybody tried to run this on WIFI instead over Ethernet ?

### ISSUE THREAD

**Issue by cpietsch** [turingmachine/omxplayer-sync#81]
I want to do a 3 Screen setup and was wondering if you could use the master raspi as an hotspot to where the other 2 connect via wifi.
In this scenario I wouldn't have to deal with cables and a switch.

Has anybody tried this ?

**Comment by pagaille** [comment]
I did it, here are my notes : 

Install RaspAP :

`wget -q https://git.io/voEUQ -O /tmp/raspap && bash /tmp/raspap`

Fix the Pi3 scan wifi issue : 

```
sudo nano /var/www/html/includes/configure_client.php

#Replace lines # by

  exec( 'sudo wpa_cli -i wlan0 scan' );
  sleep(3);
  exec( 'sudo wpa_cli -i wlan0 scan_results',$scan_return );
  
Add the following line in sudoers :
   sudo visudo
    www-data ALL=(ALL) NOPASSWD:/sbin/wpa_cli -i wlan0 scan_results
    www-data ALL=(ALL) NOPASSWD:/sbin/wpa_cli -i wlan0 scan
```

Configure AP on master & connect the clients by connecting to http://10.3.141.1 (admin | secret)

**Comment by cpietsch** [comment]
thanks a lot for the replies !

**Comment by pagaille** [comment]
@rileycoyote87 i don’t remember :( I found that fix somewhere on Internet (could be a French forum), maybe you can enter the lines in google.

**Comment by rileycoyote87** [comment]
I only kinda got it working on wifi. Rj45 is much easier and better sync

**Comment by rileycoyote87** [comment]
I ended up using the node js sockets version of omx sync works perfect on
lan and wifi

**Comment by cpietsch** [comment]
Oh sweet! Haven't seen that one yet. https://github.com/bmoren/node-omxplayer-sync
