### ISSUE TITLE
Slave keeps syncing

### ISSUE THREAD

**Issue by Deguerry** [turingmachine/omxplayer-sync#82]
Hello,

Thanks for this wonderful tool.

I'm syncing two raspberries over wifi. I know it's not ideal, but I'm trying to make it work. I simply followed the instructions provided in the repository for installation, on two Rpi 3B with Jessie on it (2016-05-27).

The master starts nicely, and the slave follows but keeps resyncing itself, which means it freezes every few seconds and jumps forward. 

Is there a way to limit how many syncing attempts the slave can do ?

Thanks in advance

**Comment by turingmachine** [comment]
Raise the value of SYNC_TOLERANCE.
