### ISSUE TITLE
Support for cropping and rotation

### ISSUE THREAD

**Issue by whitebird** [turingmachine/omxplayer-sync#84]
The omxplayer package has support for cropping and rotating a video. For building a videowall I need synchronized playback on 12 screens.

Since it's possible to crop and rotate in omxplayer, is this also possible in omxplayer-sync?

**Comment by whitebird** [comment]
Hi @magdesign , I'll take a look at the source code and have a try. Thank you!

**Comment by magdesign** [comment]
I think cropping is done with additional flags in omxplayer, so you should be able to add the same flags behind omxplayer-sync.

**Comment by whitebird** [comment]
There are two ways for cropping, either via DBUS or via command flag. Rotation can only be done with a command flag. I believe there is a fork for setting the rotation over DBUS as well, but that's not needed in my case.

**Comment by magdesign** [comment]
Dbus commands do work well, I am often using the pause command...
