### ISSUE TITLE
generating timecode mechanically to sync video

### ISSUE THREAD

**Issue by DSPeelJ** [turingmachine/omxplayer-sync#87]
Not an issue but a question to the community.  I've used Omxplayer-sync quite sucessfully for a 24 screen presentation that ran essentially trouble free for 9 months.  We've got another project where we want to sycn an animation to match the stroke of an oil pump.  Could a rotary encoder tied to the pump spoof timecode that could be read by a slave unit to sync the video action to it?

**Comment by jblanteigne** [comment]
Oh nice. I'm actually looking for something like this but I have no idea where to start. I would be interested in helping creating such a feature.

**Comment by pramodmadhav** [comment]
I have done it with  push button. Start and stop switches are connected to master .Python script waits for the switch on gpio.
When it is pressed master starts and then slaves starts with sync .I have a blank video at the start of about 7 sec  so that when actual video starts they are all in sync.
