### ISSUE TITLE
Working Autoplay on boot!

### ISSUE THREAD

**Issue by jblanteigne** [turingmachine/omxplayer-sync#88]
Not an issue. I just figured that after spending a few hours figuring this out, I would share my solution for a simple autoplay on boot that also supports keyboard input to stop your video (ctrl+c) and edit your script.

I used this method by Matt Hollander: https://www.matthewhollander.com/play-video-on-startup-of-raspbian-on-raspberry-pi/

To make it short. You create a .sh script that launch /usr/bin/omxplayer-sync
The .sh script is launched within a terminal with a .desktop file located in /etc/xcd/autostart

**Comment by fadetofadh** [comment]
Can you share the detail method? cause those link you had dropped don't lead me to the method.

**Comment by hitesh83** [comment]
there are a few more ways to do this, you can run sh on startup via the below options. 
1- rc.local
2- systemd
3- crontab 
4- .bashrc

**Comment by fadetofadh** [comment]
Thank you for getting back to me.
After diving into many internet forums, I choose the method of creating .sh and executed it from terminal which auto-open after login.
