### ISSUE TITLE
Problem with play video from crontab

### ISSUE THREAD

**Issue by luknik360** [turingmachine/omxplayer-sync#90]
Hello

I have a weird problem, when I'm starting script in terminal everything is ok, but when I added script to crontab my video turn off after about 14 sec (always in the same time).

Someone can help me, I don't know how I can fix it. Thanks.

**Comment by turingmachine** [comment]
is this still an issue?

**Comment by 6faces** [comment]
I have the same issue - exactly at 14 seconds. Running logging from crontab I can see it's having issues with dbus:

connect: Network is unreachable
WARNING: dbus connection could not be established
[Errno 2] No such file or directory: '/tmp/omxplayerdbus.pi'
WARNING: omxplayer did not start. Try to test with `omxplayer -s OPTIONS`
WARNING: dbus connection could not be established
[Errno 2] No such file or directory: '/tmp/omxplayerdbus.pi'
WARNING: omxplayer did not start. Try to test with `omxplayer -s OPTIONS`
