### ISSUE TITLE
Videos of (slightly) different lengths

### ISSUE THREAD

**Issue by exidyboy** [turingmachine/omxplayer-sync#91]
You can run different files as long as you name them all the same. I'm running 24 different files, all with the same name and encoded identically and haven't had any issues. They are all the same length though. Perhaps of the master is the longest one...  They will all follow the master so if they are longer, they'll restart when the master does.

_Originally posted by @DSPeelJ in https://github.com/turingmachine/omxplayer-sync/issues/76#issuecomment-401187445_

**Comment by exidyboy** [comment]
Not an issue but a question related to the above. I am setting up a diptych and one video is one frame longer than the other. I would rather not ask the artist to remaster the video and would prefer for quality reasons not to trim one PAL frame and re-compress from H264 to H264 myself.

I am not sure because of the grammar "Perhaps of the master is the longest one" if @DSPeelJ is suggesting to make the slave video the longer one or not? This makes sense intuitively but wanted to check if anyone has practical experience. I always ask artists to provide clips that are the identical length "to the frame" but these were encoded a few years ago for different media players in a different gallery and I don't want to be pedantic about it if it doesn't matter.

**Comment by DSPeelJ** [comment]
Sorry for the typo. I would make the slave the longer one initially.  Simple enough to try both ways.  I haven't tried different lengths though.

**Comment by turingmachine** [comment]
A difference of one frame in length shouldn't have much of an effect.
