### ISSUE TITLE
Documentation on Pi Version and Raspbian Version

### ISSUE THREAD

**Issue by roman-tub** [turingmachine/omxplayer-sync#92]
What do you guys think about gathering information on the working versions out there. 
What exact Raspbian Image and what exact Pi Model did you use? 

For example this: https://www.khm.de/~sievers/net/omxplayer-sync.html 

Works only for Raspberry 3 Model B. 
On Raspberry 1 Model B+ the master stops playing after 4 seconds with autoplay on boot. No error messages, which is really an error I didn't expect caused by the board model.

**Comment by jblanteigne** [comment]
I'd like to point out that I had to follow these instructions to get omxplayer-sync to work on raspbian Stretch.

https://github.com/turingmachine/omxplayer-sync/issues/80#issuecomment-443665544

**Comment by pramodmadhav** [comment]
if you only install omxplayer-sync and its dependencies it works on raspberry pi4 and latest OS
