### ISSUE TITLE
Time limit

### ISSUE THREAD

**Issue by chatonsky** [turingmachine/omxplayer-sync#93]
I installed omxplayer-sync correctly. I can play a video of a maximum duration of 1 hour. Beyond that, with the same compression settings, the video does not start. A brief black screen appears. I have extended the sleep parameter to 20.
Is there a time limit or parameter I haven't seen?

**Comment by 5shekel** [comment]
turn on verbose mode to see debug info,  you can skip close to the loop point on the master using the left/right keys. to save you from the hour long suspense

**Comment by turingmachine** [comment]
@chatonsky does your video start with omxplayer?

**Comment by chatonsky** [comment]
Thank you for your advice. I simply extended the sleep time in the code.
