### ISSUE TITLE
Player options gone?

### ISSUE THREAD

**Issue by phbaars** [turingmachine/omxplayer-sync#95]
OMXplayer has the options --win and --crop. How can I use these options with OMXplayer-sync?

**Comment by hitesh83** [comment]
You need to hardcore those values in omxplayer-sync file.
I had used --win same way

**Comment by phbaars** [comment]
Hi,
Thanks for your email. I added the command line options –win and –crop to omxplayer-sync file. My first ever python experience  with a steep learning curve.
I placed the video on a ramdisk for speed. It syncs ok, but why does the client stand still sometimes? It seems to get out of sync.
Best regards
