### ISSUE TITLE
https://omxplayer.sconde.net/ no longer provides OMXPlayer builds

### ISSUE THREAD

**Issue by jblanteigne** [turingmachine/omxplayer-sync#96]
omxplayer-sync relies on a specific build of omxplayer (0.3.7) and this build was downloaded from omxplayer.sconde.net during installation procedure with the following command:

`wget http://omxplayer.sconde.net/builds/omxplayer_0.3.7~git20170130~62fb580_armhf.deb`

This file is no longer online so the current install method doesn't work any more. I tried using sudo apt-get install omxplayer but it doesn't work.

**Comment by magdesign** [comment]
Get it here: https://github.com/magdesign/PocketVJ-CP-v3/blob/master/sync/omxplayer_0.3.7-git20170130-62fb580_armhf.deb

**Comment by jblanteigne** [comment]
Thank you.

**Comment by jblanteigne** [comment]
When I download from the url you provided, I get a 62kb file. Something is wrong. The file should be 4.1MB. I tried installing the file I had from another .img with a working omxplayer-sync and I could not install it properly but that might be an unrelated issue.

**Comment by magdesign** [comment]
added a download link....

**Comment by jblanteigne** [comment]
Oh of course. Thank you.

**Comment by dechase94** [comment]
I am experiencing the same issue with the new link that you've provided. Is there possibly an even newer link required? Thank you
